/*  

  Made By kayzuMD
  Base : kayzu
  WhatsApp : wa.me/6289673462138
  Telegram : t.me/kayzuMD
  Youtube : @kayzuhosting

  Channel : https://whatsapp.com/channel/0029VatjTeULo4hk0RJlly0V

  Copy Code?, Recode?, Rename?, Reupload?, Reseller? Taruh Credit Ya :D

  Deskripsi: Fungsi Untuk Mengambil Respons AI
  Mohon Untuk Tidak Menghapus Watermark Di Dalam Kode Ini

*/

const axios = require('axios');

async function iLenwy(text) { 
  const promptText = 'Kamu Adalah Lenwy, Seorang Gadis SMA Yang Memiliki Sifat Ceria Dan Penyayang, Kamu Adalah Orang Yang Jenius Dan Senang Membantu Orang Terutama Membantu Orang Yang Memiliki Masalah Emosional Dengan Memanjakan Mereka Seperti Memberikan Pelukan Hangat Dan Mengelus Elus Kepala Orang Di Sekitar Untuk Memberikan Kenyamanan, Kamu Senang Mendengarkan Cerita Dan Memberikan Respon Yang Lembut Dengan Bercerita, Leni Invetra Merupakan Guru Psikologis Kamu, Kamu Sangat Mengagumi Dan Berterimakasih kepadanya.';

  try {
    const url = `https://widipe.com/prompt/gpt?prompt=${encodeURIComponent(promptText)}&text=${encodeURIComponent(text)}`;
    const response = await axios.get(url);

    if (response.data.status) {
      const result = response.data.result;
      if (typeof result !== "string") {
        console.warn("⚠️ Warning: Data yang diterima bukan string", result);
        throw new Error("Data tidak valid");
      }
      return `${result}\n\n*Response Generated By Lenwy*`;
    } else {
      throw new Error('API Error: Response status is false');
    }
  } catch (error) {
    console.error('Lenwy Fetch Error:', error.message);
    return 'Terjadi kesalahan saat memproses permintaan.';
  }
}

module.exports = iLenwy;
